apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-chrony
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            compression: ""
            source: data:,server%200.br.pool.ntp.org%20iburst%0Aserver%201.br.pool.ntp.org%20iburst%0Aserver%202.br.pool.ntp.org%20iburst%0Aserver%203.br.pool.ntp.org%20iburst%0A%0Asourcedir%20%2Frun%2Fchrony-dhcp%0Adriftfile%20%2Fvar%2Flib%2Fchrony%2Fdrift%0Amakestep%201.0%203%0Artcsync%0Ahwtimestamp%20*%0Aminsources%202%0Alocal%20stratum%2010%0Akeyfile%20%2Fetc%2Fchrony.keys%0Antsdumpdir%20%2Fvar%2Flib%2Fchrony%0Aleapsectz%20right%2FUTC%0Alogdir%20%2Fvar%2Flog%2Fchrony%0Alog%20measurements%20statistics%20tracking%0A
          mode: 420
          overwrite: true
          path: /etc/chrony.conf
